name: Create infra VPC Subnets for GH Runner
on:
  workflow_dispatch:
    inputs:
      EnvName:
        description: 'Environment Where Infra to be Deployed'
        type: choice
        required: true
        default: 'Dev'
        options:
          - Dev
          - Prod
          - PPE
          - STG
      Service:
        description: 'Choose the Service you wish to Deploy'
        required: true
        type: choice
        default: 'vpc'
        options:
          - vpc
          - ec2
          - lambda
          - ecs
      S3Bucket:
        description: 'Choose S3 bucket name for Terraform Backend Statefile'
        required: true
        type: choice
        default: 'gh-runners'
        options:
          - gh-runners
          - gh-test


env:
  REPO_NAME: "${{ github.event.repository.name }}"
  SERVICE_DIR: "./infra/${{ github.event.inputs.Service }}"
defaults:
  run:
    shell: bash

permissions:
 id-token: write
 contents: read
 actions: read
 security-events: write
 packages: read

jobs:
  build:
    name: create-gh-infra
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v5
      with:
          fetch-depth: 0

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v5
      with:
        role-to-assume: arn:aws:iam::xxxxxxxxxx:role/gh-infra
        aws-region: us-east-1

    - name: Setup Terraform with specified version on the runner
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0

    - name: Terraform format
      id: fmt
      run: terraform fmt -check && terraform fmt --recursive
      working-directory: ${{ env.SERVICE_DIR }}
    - name: Terraform init
      id: init
      run: terraform init -backend-config="bucket=${{ github.event.inputs.S3Bucket }}" -backend-config="key=${{ github.event.inputs.EnvName }}/VPC/${{ github.event.inputs.Service }}.tf" -backend-config="region=us-east-1" 
      working-directory: ${{ env.SERVICE_DIR }}
    - name: Terraform validate
      id: validate
      run: terraform validate
      working-directory: ${{ env.SERVICE_DIR }}
    - name: Terraform plan 
      id: plan
      run: terraform plan -var="region=us-east-1" -var="envname=${{ github.event.inputs.EnvName }}"  -detailed-exitcode
      working-directory: ${{ env.SERVICE_DIR }}
      continue-on-error: true
    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      run: exit 1
    - name: Terraform Apply
      run: terraform apply  -var="region=us-east-1" -var="envname=${{ github.event.inputs.EnvName }}" -auto-approve -parallelism=20
      working-directory: ${{ env.SERVICE_DIR }}
